### ISSUE TITLE
Add pre and post events for states

### ISSUE THREAD

**Issue by salaboy** [salaboy/knative-workflow-runner#2]
Add hooks to states to emit CloudEvents when entering and when exiting the current state.
It should look like this: 

```
  InQueue:
    pre: 
      InQueueEnteredEvent
    post:
      InQueueExitedEvent
    events:
      ExitedQueue: BuyingTickets
      AbandonedQueue: NoTicketsPurchased
  BuyingTickets:
    events:
      TicketsReserved: PayingTickets
```

This should emit `InQueueEnteredEvent` and `InQueueExitedEvent` CloudEvents using the string as Types, the data of the event should be the context of the workflow and we can allow overriding more CloudEvents parameters with something like this: 

```
  InQueue:
    pre: 
      InQueueEnteredEvent: 
        ce-version: 
        ce-source: 
```
